FROM python:3.6

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        netcat \
    && apt-get clean

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip install -r requirements.txt

COPY ./entrypoint-prod.sh /usr/src/app/entrypoint.sh

COPY . /usr/src/app

CMD ["./entrypoint.sh"]
